### PR TITLE
Implemented a clone of a New York Times article page.

### PR DESCRIPTION
**Pull request by pointerish**
We have implemented the following:

- Navbar
- Main article content along with the required images
- Aside containing the "Editor's Picks" section
- Footer

### CODE REVIEW

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @pointerish and @che30
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

- [x] Add padding top in navbar
- [x] **Editors’ Picks** aside should be aligned with respect to **Thanks for reading The Times.** ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html))
- [ ] Footer should have a fixed position (it sticks to the bottom part of the screen [Example](https://user-images.githubusercontent.com/29689273/94274463-2cfd5f80-ff5f-11ea-88bf-7b043d865f93.png)) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)) ([screenshot](https://user-images.githubusercontent.com/29689273/94273983-8fa22b80-ff5e-11ea-9a83-89a598106bcd.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

### Navbar
- [ ] **The Theory of Inflation's** image is overlapping on the navbar, please fix this issue

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://pointerish.github.io/NYT-Clone-Page/)|
|:---:|:---:|
|source-page|clone|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by umairarshadbutt** [comment]
Sorry, I forgot to mention the Linter issue.
Please Fix the linter issue too.

**Comment by pointerish** [comment]
Hi @umairarshadbutt, we completed the changes and everything looks good. Thank you for your feedback!

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

Hi, @pointerish, and @che30  congratulations on completing your project. I see you have successfully implemented all the changes requested by the previous TSE. 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project. 


### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Pull request merged**
